version: "3"

services:

  spark-master:
    image: ungawatkt/rpi-spark-210
    command: ./start-master
    networks:
      - overnet
    deploy:
      placement:
        constraints: [node.hostname == controller]

  spark-worker:
    image: ungawatkt/rpi-spark-210
    command: ./start-worker
    depends_on:
      - spark-master 
    networks:
      - overnet
    environment:
      - SPARK_WORKER_CORES=1
    #deploy:
      #placement:
        #constraints: [node.hostname != controller]

  spark-proxy:
    image: ungawatkt/rpi-haproxy
    # command: sleep 30000
    command: haproxy -f /xcb_data/haproxy.cfg
    # command: haproxy -f /usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 80:80
      - 8080:8080
      - 7077:7077
      - 6066:6066
    networks:
      - overnet
    depends_on:
      - spark-master
    deploy:
      mode: replicated
      placement:
        constraints: [node.hostname == controller]
    volumes:
      - ./rpi-haproxy:/xcb_data

networks:
    overnet:
