version: "3"

services:

  hadoop-master:
    image: rpi-hadoop
    command: bash -c "service ssh start && sleep 30000000"
    networks:
      - overnet
    ports:
      - "8088:8088"
      - "50090:50090"
      - "19888:19888"
    deploy:
      placement:
        constraints: [node.hostname == controller]

  hadoop-slave:
    image: rpi-hadoop
    command: bash -c "service ssh start && sleep 30000000"
    networks:
      - overnet

networks:
    overnet:
